name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2

      - name: Run Docker Tests
        run: |
          cd tests/integration/docker_test
          docker-compose up -d
          docker exec drivers "deno test -A --config tsconfig.json tests/integration && deno test -A tests/unit"

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2

      - name: Run Integration Tests
        run: |
          deno test -A tests/integration --config tsconfig.json

      - name: Run Unit Tests
        run: |
          deno test -A tests/unit --config tsconfig.json

#      - name: Install Rhum
#        run: deno install -A https://raw.githubusercontent.com/drashland/rhum/rhum-cli/mod.ts
#
#      - name: Unit
#        if: matrix.os != 'windows-latest'
#        run: |
#          export PATH="~/.deno/bin:$PATH"
#          rhum-cli tests/unit/
#
#      - name: Integration
#        if: matrix.os != 'windows-latest'
#        run: |
#          export PATH="~/.deno/bin:$PATH"
#          rhum-cli tests/integration
#
#      - name: Unit Tests (windows)
#        if: matrix.os == 'windows-latest'
#        run: |
#          $env:Path += ";C:\Users\runneradmin\.deno\bin"
#          rhum-cli tests/unit
#
#      - name: Integration Tests (windows)
#        if: matrix.os == 'windows-latest'
#        run: |
#          $env:Path += ";C:\Users\runneradmin\.deno\bin"
#          rhum-cli tests/integration

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2

      - name: Lint
        run: deno lint --unstable

      - name: Formatter
        run: deno fmt --check
